DROP SCHEMA IF EXISTS bronze CASCASE;
DROP SCHEMA IF EXISTS silver CASCASE;
DROP SCHEMA IF EXISTS gold CASCASE;
DROP SCHEMA IF EXISTS audit CASCASE;

CREATE SCHEMA bronze;
CREATE SCHEMA silver;
CREATE SCHEMA gold;
CREATE SCHEMA audit;


